---
title: "Literature Review"
author: "Sam Ivey"
date: "January 30, 2015"
output: html_document
---
Given the association that I have decided to examine, I use such keywords as alcohol, alcohol abuse, and alcohol dependence. After  reading many articles on alcohol use and the health problems associated, I have decided to expand on how alcohol not only effetcs your body, but specfically your brain as well. 

Based on my reading of the articles and through research I have gathered a few common aspects found throughout:

Alcohol is a drug that is abused intentionally and unintentionally. Being educated on the health problems that can come from alcohol abuse is very important. I found throughout that alcohol is known to damage not only certain body functions such as liver functionality, it can cause mental issues as well. Associating alcohol use and health problems has a variety of factors including age, weight, and gender 

One of the most common mental problems that can spawn from alcohol abuse are depression, anxiety, memory loss, etc.

My goal through this research is to provide specific brain functions that alcohol can alter. I will examine how the abuse of alcohol damages the brain and how heavy abuse can cause major alterations in ones personality. I want to explicitly examine how different variations of abuse of alcohol can lead to certain problems and how these problems effect different people given certain variables. My variables will include gender, weight, height, age, etc. 


Bibliography

Bell, Steven, and Annie Britton. "An Exploration Of The Dynamic Longitudinal Relationship Between Mental Health And Alcohol Consumption: A Prospective Cohort Study." BMC Medicine 12.1 (2014): 105-134. Academic Search Complete. Web. 6 Feb. 2015.

Chisolm, Deena J.1,2, Deena.Chisolm@NationwideChildrens.org, et al. "Health Literacy, Alcohol Expectancies, And Alcohol Use Behaviors In Teens." Patient Education & Counseling 97.2 (2014): 291-296. Education Source. Web. 6 Feb. 2015.

Desfosses, Melissa, et al. "The Relationship Between Neuropsychological Functioning And Mental Health Outcomes Of Chronic Alcohol Users Involved In Counselling: Prediction Of Treatment Outcome." Australian Psychologist 49.5 (2014): 287-296. PsycINFO. Web. 6 Feb. 2015.

Ismayilova, Leyla, et al. "Mental Health And Migration: Depression, Alcohol Abuse, And Access To Health Care Among Migrants In Central Asia." Journal Of Immigrant & Minority Health 16.6 (2014): 1138-1148. Academic Search Complete. Web. 6 Feb. 2015.

Reingle, Jennifer M., et al. "On The Pervasiveness Of Event-Specific Alcohol Use, General Substance Use, And Mental Health Problems As Risk Factors For Intimate Partner Violence." Journal Of Interpersonal Violence 29.16 (2014): 2951-2970. PsycINFO. Web. 6 Feb. 2015.

